
job-debian9-yocto-sumo:
  stage: build
  tags: [ "docker-debian9" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-yocto:latest
#  only:
#    variables:
#      - $NIGHTLY_MASTER
  cache:
    key: yocto-cache-key
    paths:
      - build/tmp/
      - build/deploy/
      - build/work/
      - build/work-shared/
      - build/sstate-cache/
      - build/downloads/
  script:
    - export WORKSPACE_PATH="$(pwd)"
    - cd /home/build/poky
    - source oe-init-build-env
    - bitbake -f linphone-sdk 2>&1 | tee bitbake_build.log
    - cd $WORKSPACE_PATH
    - ln -s /home/build/poky/build ./
#Gitlab doesn't handle cache and artifacts paths outside of project workspace (/builds/$WORKSPACE/$PROJECT_NAME)
  artifacts:
    paths:
      - build/bitbake_build.log
      - build/tmp/deploy/ipk/**/linphone-sdk*.ipk
